var message = "Hello world";
console.log(message);
console.log(mes);
var value;
value = 'Ram';
console.log('welcome', value);
console.log(typeof (value));
value = 200;
console.log('val', value);
console.log(typeof (value));
var msg = 'hello';
msg = 90;
console.log(msg);
